### ISSUE TITLE
GPG and checksum validation seems broken

### ISSUE THREAD

**Issue by eliecharra** [wbeuil/dctlenv#13]
![image](https://user-images.githubusercontent.com/6154987/108491257-f9bbc400-72a3-11eb-8b75-b1943c59b3d6.png)

And btw the checksum verification should be done by default, and not only when GPG signature is turned on.

**Comment by wbeuil** [comment]
By default the checksum should be done:
![image](https://user-images.githubusercontent.com/8110579/110144141-4b05a080-7dd8-11eb-99d1-e15a97cc61fc.png)

Don't know why on your screenshot it says that no SHA256 file was found ... Can you retry a simple `dctlenv install 0.5.0`.

As for GPG sign validation, I'm not sure we should enforce it since not everybody wants to keep GPG public keys in their device, hence the opt-in feature.

**Comment by eliecharra** [comment]
cannot reproduce using the latest version 

![image](https://user-images.githubusercontent.com/6154987/110304686-2c7fef00-7ffc-11eb-98fd-5b477cb21d17.png)

Closing for now
